### ISSUE TITLE
Q群搜不到啊

### ISSUE THREAD

**Issue by ghost** [MathsFans/Euclidea#10]
本Repo Q群：527621502——无搜索结果

**Comment by Tairraos** [comment]
Send by mobile, sorry for typo.
-- Xiaole Tao

**Comment by ghost** [comment]
What is the correct number?

**Comment by Tairraos** [comment]
u got the right number, make sure you did right search. as i tried there is no issue.

Send by mobile, sorry for typo.
-- Xiaole Tao

**Comment by gsdevcn** [comment]
I think the Q-group number is correct. Closing this issue.
