### ISSUE TITLE
12.6 2V 可作10L10E解

### ISSUE THREAD

**Issue by GreenYun** [MathsFans/Euclidea#13]
共用7L7E已作的辅助圆，减少步数。
使用共同点可以免去画两个辅助圆即有定点可作等边三角形。

**Comment by Tairraos** [comment]
能提供解法步骤吗？谢谢

**Comment by Tairraos** [comment]
或者发起一个pull request。你的名字会显示在commit里。

**Comment by GreenYun** [comment]
已提交pull request，請查看

**Comment by gsdevcn** [comment]
多谢您的方法，但是2V的解法游戏里并不算记录，所以用任意的E或者V对记录都没有影响。
