### ISSUE TITLE
当组成某个角的两条边都不存在，而是用3个点来表示这个角，如何用4E作该角的平分线

### ISSUE THREAD

**Issue by szp14** [MathsFans/Euclidea#17]
在题目2.1中可以知道作角平分线需要4E，但是题目2.1中这个角的两条边是已经存在的。如果这个角的两条边不存在，是否还能用4E作出角平分线？
在题目10.9(将一个线段分为1:5的两个部分)的4L解法中，第4步就是利用3个点来作角平分线，这个角的两条边此时还没有被画出来，也就是不存在的。

**Comment by gsdevcn** [comment]
我问过Euclidea作者，这确实是一个缺陷，但是他不准备改了。
