### ISSUE TITLE
建议更换图源

### ISSUE THREAD

**Issue by Charlie-zzy** [MathsFans/Euclidea#22]
由于Github加载速度慢，再加上网站有大量图片，建议将所有图片链接
```https://mathsfans.github.io/Euclidea/xxx```
批量改为
```https://cdn.jsdelivr.net/gh/mathsfans/Euclidea/xxx```。
（搜索`https://mathsfans.github.io/Euclidea/`替换为`https://cdn.jsdelivr.net/gh/mathsfans/Euclidea/`即可。）

**Comment by Tairraos** [comment]
谢谢，试了下海外IP访问会403，报告一个奇怪的错误。
Package size exceeded the configured limit of 50 MB. Try https://github.com/mathsfans/Euclidea/tree/master/ instead.

**Comment by Charlie-zzy** [comment]
> 谢谢，试了下海外IP访问会403，报告一个奇怪的错误。
> Package size exceeded the configured limit of 50 MB. Try https://github.com/mathsfans/Euclidea/tree/master/ instead.

我也是，这是因为jsdelivr不能访问太大的仓库，不帮你了（

**Comment by Charlie-zzy** [comment]
不过单独文件是能正常访问的。

**Comment by Tairraos** [comment]
算了，大家坚持下用github吧。跟世界走在一起，不要搞墙内小世界。
