### ISSUE TITLE
是否支持gif Gif Support

### ISSUE THREAD

**Issue by gaoyaoxin** [MathsFans/Euclidea#4]
md文件增加有关gif的内容，并改变genBase.js
[GIF]仍无法显示与PNG相似的弹窗效果

add contents about gif in .md & genBase.js files
the same effect as PNG is not displayed

![01](https://cloud.githubusercontent.com/assets/20694974/20235657/e8707adc-a8d2-11e6-9508-e745b18169aa.png)
![02](https://cloud.githubusercontent.com/assets/20694974/20235660/eceae8b8-a8d2-11e6-805c-6dd51f5a6b7f.png)

https://github.com/gaoyaoxin/Euclidea123/tree/gh-pages
http://www.gaoyaoxin.cf/Euclidea123

**Comment by Tairraos** [comment]
GIF弹窗功能已经改好。现在 ! [xxx]（xxx.gif） 显示成链接， 没有叹号的，会显示成button，点击后会弹窗显示。谢谢
