### ISSUE TITLE
能否将master 和gh-pages合并 combine master&gh-pages together

### ISSUE THREAD

**Issue by gaoyaoxin** [MathsFans/Euclidea#7]
很多改变是在master上直接完成的，而托管网站的gh-pages很少改动，网站上的内容更新滞后。能否考虑将gh-pages中的文件移动至master，删除gh-pages分支。将网站托管到master分支（正如我的fork https://github.com/gaoyaoxin/Euclidea）
如果可以，我将发一个pull request，同时包含gif和其他更新

The website is hosted on gh-pages while newly changed files were all on master branch, so the website doesnot display the newest changes.
Please consider combining master&gh-pages together(moving all necessary files for website building to master branch)
See my fork with master&gh-pages combined together https://github.com/gaoyaoxin/Euclidea

**Comment by gsdevcn** [comment]
我每次都会合并master到gh-pages，不知道@Tairros怎么看。。。

**Comment by gaoyaoxin** [comment]
可以更精简吧, IMO

**Comment by Tairraos** [comment]
gh-page的设计不是为了增加维护障碍，纯粹是为了设置语义上的隔离。
euclidea这个repo原旨是为游戏作解，开源交付的是游戏的解，所以master是只维护解的。
page通过merge master动作同步到新的解，然后通过js动态更新page。
github定义gh-page分支也是为了践行这种交付内容和页面分离的理念。
我自己[还有一个repo](https://github.com/Tairraos/Geometry-Solving)也是作了同样的隔离。

我们团队另有一个tchisla repo是直接在master上维护page的，开始的时候维护非常频繁，为了方便维护所以没有创建gh-page branch。

你的建议可以接受，我来把page merge回master。如果有兴趣，你可以加群，加入g-fans团队呀

**Comment by gaoyaoxin** [comment]
感谢楼上的解答，作为新手，我的考虑并不十分深入，见笑！
另，已入群中
